# Generated by Django 5.1.6 on 2025-04-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0002_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
